"""initial

Revision ID: 622d0f7855b7
Revises: 
Create Date: 2026-06-30 18:01:01.092198
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '622d0f7855b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CAMERA_OFFLINE', 'INVALID_QR', 'DUPLICATE_COUNT', 'INVENTORY_MISMATCH', name='alert_type_enum', create_constraint=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum', create_constraint=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('boxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('qr_data', sa.String(length=255), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=False, comment='AI engine camera_id (e.g. cam_1)'),
    sa.Column('status', sa.Enum('IN_TRANSIT', 'STORED', 'DISPATCHED', 'LOST', name='box_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boxes_camera_id'), 'boxes', ['camera_id'], unique=False)
    op.create_index(op.f('ix_boxes_qr_data'), 'boxes', ['qr_data'], unique=False)
    op.create_index(op.f('ix_boxes_tracking_id'), 'boxes', ['tracking_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'OFFLINE', name='camera_status_enum', create_constraint=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_name'), 'cameras', ['camera_name'], unique=False)
    op.create_index(op.f('ix_cameras_warehouse_id'), 'cameras', ['warehouse_id'], unique=False)
    op.create_table('count_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=False, comment='AI engine camera_id (e.g. cam_1)'),
    sa.Column('movement_type', sa.Enum('ENTRY', 'EXIT', name='movement_type_enum', create_constraint=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_count_logs_box_id'), 'count_logs', ['box_id'], unique=False)
    op.create_index(op.f('ix_count_logs_camera_id'), 'count_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_count_logs_timestamp'), 'count_logs', ['timestamp'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_product_code'), 'inventory', ['product_code'], unique=True)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_code'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_count_logs_timestamp'), table_name='count_logs')
    op.drop_index(op.f('ix_count_logs_camera_id'), table_name='count_logs')
    op.drop_index(op.f('ix_count_logs_box_id'), table_name='count_logs')
    op.drop_table('count_logs')
    op.drop_index(op.f('ix_cameras_warehouse_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_name'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_boxes_tracking_id'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_qr_data'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_camera_id'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
